spring:
  application:
    name: agri_supplies_shop
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  liquibase:
    enabled: false

jwt:
  signer-key: ${SIGNER_KEY}
  valid-duration: 36000 # in second
  refreshable-duration: 36000 # in second
file:
  upload-dir: D:\\university\\NLCS\\project\\images
vnpay:
  vnp_TmnCode: ${VNP_TMN_CODE}
  vnp_HashSecret: ${VNP_HASH_SECRET}
  vnp_ReturnUrl: http://localhost:3000/payments/payment_callback
  vnp_PayUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  vnp_ApiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction






